ag_shopping_mart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='product_list'),
    path('shop', views.product_list, name='product_list'),
    path('login', views.Login, name='login'),
    path('register', views.Register, name='login'),
    path('logout', views.USR_Logout, name='logout'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('contact', views.Contact, name='contact'),
    path('abt-us', views.About),
    # path('complain', views.complain),
    

]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class ContactUs(models.Model):

    Name = models.CharField(max_length=60)
    Subject =  models.CharField(max_length=60)
    Email = models.CharField(max_length=100)
    Phone = models.IntegerField()
    Chat =  models.CharField(max_length=6000)
    def __str__(self):
        return self.Name +" "+ str(self.id)
    


class Home_Slider(models.Model):

    Name = models.CharField(max_length=60)
    image = models.ImageField(upload_to='home/sliders')
    Link =models.CharField(max_length=600)
    def __str__(self):
        return self.Name

class Block_Buster_Deal(models.Model):
    Item = models.ForeignKey(Product,on_delete=models.CASCADE)


    

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from shop.models import ContactUs
 

 
class UserRegisterForm(UserCreationForm):
    username = forms.EmailField(widget = forms.TextInput(attrs={'type': 'Email', 'class': 'form-control','placeholder':'Email'}))
    # email = forms.EmailField(widget = forms.TextInput(attrs={'type': 'text', 'class': 'form-control','placeholder':'Email'}))
    phone_no = forms.CharField(max_length = 20,widget = forms.NumberInput(attrs={'type': 'tel', 'class': 'form-control','placeholder':'Phone'}))
    first_name = forms.CharField(max_length = 20,widget = forms.TextInput(attrs={'type': 'text', 'class': 'form-control','placeholder':'First Name'}))
    last_name = forms.CharField(max_length = 20,widget = forms.TextInput(attrs={'type': 'text', 'class': 'form-control','placeholder':'Last Name'}))
    password1 = forms.CharField(max_length = 20,widget = forms.PasswordInput(attrs={'type': 'password', 'class': 'form-control','placeholder':'Password'}))
    password2 = forms.CharField(max_length = 20,widget = forms.PasswordInput(attrs={'type': 'password', 'class': 'form-control','placeholder':'Confirm Password'}),label='')
    class Meta:
        model = User
        def __init__(self, *args, **kwargs):
            super(UserRegisterForm, self).__init__(*args, **kwargs)
            self.fields['password2'].label = ""
        fields = ['username', 'phone_no', 'password1', 'password2']
class ContactUsForm(forms.ModelForm):
    Name = forms.CharField(widget = forms.TextInput(attrs={'type': 'text','placeholder':'Name'}))
    Subject = forms.CharField(widget = forms.TextInput(attrs={'type': 'text', 'placeholder':'Subject'}))
    Email = forms.EmailField(widget = forms.TextInput(attrs={'type': 'email','placeholder':'Email'}))
    Phone = forms.CharField(widget = forms.NumberInput(attrs={'type': 'text', 'placeholder':'Phone', "name":"telephone",'id':"telephone_input"}))
    Subject = forms.CharField(max_length = 20,widget = forms.NumberInput(attrs={'type': 'text', 'placeholder':'Subject'}))
    Chat = forms.CharField(max_length = 6000,widget = forms.Textarea(attrs={'type': 'text', 'placeholder':'Message',"cols":"30" ,"rows":"5" }))
    class Meta:
        model = ContactUs
        fields = ['Name', 'Subject', 'Email', 'Phone', 'Chat','Subject']

shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from cart.forms import CartAddProductForm
from .models import Category, Product ,Home_Slider,Block_Buster_Deal
# Authentication
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.csrf import csrf_protect

# Registration
from django.contrib import messages
from django.contrib.auth import authenticate, login

from .forms import UserRegisterForm , ContactUsForm

def home(request):
    Slider_Img  =  Home_Slider.objects.all()
    Blockbuster =  Block_Buster_Deal.objects.all()
    products_details = Product.objects.filter(id__in=Blockbuster.values("Item"))
    # products_details = Product.objects.filter(id__in=[i.Item for i in Block_Buster_Deal.objects.all()])
    # products_details = Block_Buster_Deal.objects.filter(Item__in=[i.id for i in Product.objects.filter()])

    print(products_details)
    return render(request,"shop/home.html",{"slider":Slider_Img,"products":products_details})

@ensure_csrf_cookie
@csrf_protect
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'shop/product/list.html', context)




def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, 'shop/product/detail.html', context)


def Login(request):
        if request.method=='POST':
            USR_NAME = request.POST['username']
            PASSWORD = request.POST['password']
            USR = authenticate(username=USR_NAME,password= PASSWORD)
            if USR is not None:
                login(request,USR)
                return redirect('/')
                
            
            return render(request,"others/login.html")
        if request.user.is_authenticated:
            return redirect('/')
        return render(request,"others/login.html")


def Register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created ! You are now able to log in')
            return redirect('/login')
    else:
        form = UserRegisterForm()
    return render(request, 'others/register.html', {'form': form, 'title':'register here'})

def Contact(request):
    form = ContactUsForm()
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            # form.save()
            complains = form.save()
            print(complains.id)
            messages.success(request, f'Your account has been created ! You are now able to log in')
            return render(request,'others/Complain.html',{"form":complains})
    
    else:
        return render(request, 'others/contact.html',{"form":form})


def About(request):
    return render(request,"others/About.html")
def USR_Logout(request):
    logout(request)
    return redirect('/')

templates/shop/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}AG SHOPPING MART{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static "fonts/icomoon/style.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="site-wrap">
        {% include 'shop/base/navbar.html' %}
        {% block content %}
        {% endblock %}
        {% include 'shop/base/footer.html' %}
    </div>
    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "js/jquery-ui.js" %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "js/aos.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/shop/base/footer.html
{% load static %}
   <footer class="site-footer border-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="footer-heading mb-4">Navigations</h3>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Sell online</a></li>
                                <li><a href="#">Features</a></li>
                                <li><a href="#">Shopping cart</a></li>
                                <li><a href="#">Store builder</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Mobile commerce</a></li>
                                <li><a href="#">Dropshipping</a></li>
                                <li><a href="#">Website development</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Point of sale</a></li>
                                <li><a href="#">Hardware</a></li>
                                <li><a href="#">Software</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <h3 class="footer-heading mb-4">Details</h3>
                    <a href="#" class="block-6">
                        <img src='{% static "img/logo2.PNG" %}' alt="Image placeholder" class="img-fluid rounded mb-4">
                        <h3 class="font-weight-light  mb-0">Best Electronics Gadgets </h3>
                        <p>Promo from january 15 &mdash; 25, 2023</p>
                    </a>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">Contact Info</h3>
                        <ul class="list-unstyled">
                            <li class="address">Orion Buisness Park 1st Floor Office No 7</li>
                            <li class="phone"><a href="tel:9653419358">+91 9156166309</a></li>
                            <li class="email">ashutoshrohitgiri786@agdevelopers.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/shop/base/navbar.html
{% load static %}
<header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                        <form action="" class="site-block-top-search">
                            <span class="icon icon-search2"></span>
                            <input type="text" class="form-control border-0" placeholder="Search">
                        </form>
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="">
                            <a href="#" class="js-logo-clone"><img src='{% static "img/logo2.PNG" %}' height="50px" alt=""></a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                {%if user.is_authenticated%}
                                <!-- <li><a href="#"></li> -->
                                <li><div class="dropdown">
                                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span class="icon icon-person"></span></a>
                                    </a>
                                  
                                    <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">Edit Profile</a></li>
                                      <li><a class="dropdown-item" href="/order/orders/">Track Orders</a></li>
                                      <li><a class="dropdown-item" href="/logout">Sign Out</a></li>
                                    </ul>
                                  </div></li>
                                
                                {% else %}
                                <li><a href="/login">Login</a></li>
                                {%endif%}
                                <li>
                                    <a href="{% url "cart:cart_detail" %}" class="site-cart">
                                        <span class="icon icon-shopping_cart"></span>
                                        <span class="count">
                                        {% with total_items=cart|length %}
                                            {% if cart|length > 0 %}
                                                {{ total_items|pluralize }}
                                            {% else %}
                                                0
                                            {% endif %}
                                        {% endwith %}
                                        </span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0"><a href="#"
                                        class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
                <ul class="site-menu js-clone-nav d-none d-md-block">
                    <li><a href="/">Home</a></li>
                    <li><a href="/shop">Shop</a></li>
                    <li><a href="/abt-us">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </div>
        </nav>
    </header>